### ISSUE TITLE
Wrong r-prefix in path names

### ISSUE THREAD

**Issue by LFriede** [techbliss/X64dbg_script_editor#1]
Hi,

when you r-prefix the path names in the first lines at the script where you add them to sys.path and use double backslashes it will result in real double backslashes, not in escaped backslashes. I downloaded the release at x64dbg/x64dbgpy and wondered y it fails not finding the "icons.ico" module.
Removing the r-prefixes made it run for me. (lines 38, 39 & 41)

**Comment by techbliss** [comment]
did it not find the icon.ico module?

the 

``` try:
    import ico
except ImportError:
    import icons.ico
```

I cannot reproduce the issue if removing the r-prefix (.lines 38, 39 & 41)

both works here.

did you remove r-prefix also in line 42 ?

was a left over from where i had a problem if you where to run the editor outside of x64dbg.

it simply had some trouble finding the icons at one point when writing this.

if you like to run it our side of x64dbg unquote end end of script

```
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication.instance() #enable for usage outside x64dbg
    if not app: #enable for usage outside x64dbg
        app = QtWidgets.QApplication([]) #enable for usage outside x64dbg
    MainWindow = MyWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.resize(1000, 600)
    MainWindow.show()
    app.exec_() #enable for usage outside x64dbg
```

**Comment by LFriede** [comment]
Sorry, wrong information from me. Now i know why you can't reproduce it, i'll describe my setup for you so you can and see what i mean.

To reproduce the error the following setup was done by me:
Fresh snapshot of x32dbg, downloaded the release at x64dbg/x64dbgpy and extracted the content of the "x64dbgpy-37d3f5bb.zip". Then i put PyQt5 to site-packages because he was not seeing this in plugin directory too. Started x32dbg and tryed to load the editor script. Then it will fail with:
`Traceback (most recent call last):
  File "D:\Reversing Tools\x64dbg\x32\plugins\x64dbgpy\x64dbg_editor\x64dbg_editor.py", line 58, in <module>
    import icons.ico
ImportError: No module named ico`
The problem was that in this release the script is executed in "plugins\x64dbgpy\x64dbg_editor" and not in "plugins\x64dbg_editor", so it's not your fault ;) Copying it to "plugins\x64dbg_editor" fixed it for me, i just thought it was because of the r-prefix, missed that while trying around, sorry.

But it's still wrong, it still should be fixed. To prove it you can load the editor in x32dbg, after starting it goto the log window, switch the command line to python and type "print(sys.path)" for me it results in the following:
`['D:\\Reversing Tools\\x64dbg\\x32\\icons', 'D:\\Reversing Tools\\x64dbg\\x32', 'D:\\Reversing Tools\\x64dbg\\x32\\\\plugins\\\\x64dbg_editor', 'D:\\Reversing Tools\\x64dbg\\x32\\\\plugins\\\\x64dbg_editor\\\\icons', 'D:\\REVERS~1\\x64dbg\\x32\\plugins\\x64dbgpy', 'C:\\Windows\\system32\\python27.zip', 'D:\\PROGRA~2\\Python27\\DLLs', 'D:\\PROGRA~2\\Python27\\lib', 'D:\\PROGRA~2\\Python27\\lib\\plat-win', 'D:\\PROGRA~2\\Python27\\lib\\lib-tk', 'D:\\Reversing Tools\\x64dbg\\x32', 'D:\\PROGRA~2\\Python27', 'D:\\PROGRA~2\\Python27\\lib\\site-packages']
`

Here you can see the four backslashes instead of two, this was fixed after removing the r-prefix so i thought that made it run for me.

Line 42 is correct because there is only one backslash in the string.

**Comment by techbliss** [comment]
The editor is supposed to be in x64 or x32\plugins\x64dbg_editor\x64dbg_editor.py

i have made a release with the python template https://github.com/techbliss/x64dbgpy-Plugin-Template, and i thought i uploaded it last weekend.Gonna do that tommorow.

I agree with with double backslashes, i can fix that when i upload the plugin loader for the editor.

here is temp plugin loader for the editor, find it under plugins menu in x64dbg.
place it in x64 or x32\plugins\

and editor in x64 or x32\plugins\x64dbg_editor\x64dbg_editor.py

[plugins.zip](https://github.com/techbliss/X64dbg_script_editor/files/389349/plugins.zip)

**Comment by LFriede** [comment]
Thank you.
