### ISSUE TITLE
Reopen the editor windows return [PYTHON] File does not exist...

### ISSUE THREAD

**Issue by bruce30262** [techbliss/X64dbg_script_editor#5]
Environment:
* Windows 10 64 bit 1703
* x64dbg : snapshot_2017-06-30_19-50
* x64dbgpy : latest version ( [link](https://ci.appveyor.com/project/mrexodia/x64dbg-python/build/artifacts) )

***
Open x64dbg --> plugin --> x64dbgpy-Editor, everything works fine.
But after I close the editor window and tried to re-open the editor, it didn't launch and displayed the following message in the log tab:
```
[PYTHON] Executing script: "plugins\X64Dbg_editor\Editor_x64dbg.py"
[PYTHON] File does not exist...
```
This happens in both w32dbg.exe & x64dbg.exe :(

**Comment by techbliss** [comment]
I thought i fixed this.
Can you try lastest code(not release) just pushed
https://github.com/techbliss/X64dbg_script_editor/blob/master/X64Dbg_editor/Editor_x64dbg.py

**Comment by techbliss** [comment]
Okay seems to work, updated release.
https://github.com/techbliss/X64dbg_script_editor/releases
Thank you once again.

**Comment by bruce30262** [comment]
the latest code work !!   \\:smile:/
